### ISSUE TITLE
bug: on_removed_notification_add

### ISSUE THREAD

**Issue by zhangningboo** [mvniekerk/tokio-cron-scheduler#94]
jon.on_removed_notification_add is not working. Anything wrong?

```rust
use anyhow::Ok;
use tracing::{Level, info};
use tracing_subscriber::FmtSubscriber;
use tokio_cron_scheduler::{Job, JobScheduler};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let subscriber = FmtSubscriber::builder()
        .with_max_level(Level::TRACE)
        .finish();
    tracing::subscriber::set_global_default(subscriber)
        .expect("Setting default subscriber failed");

    let scheduler_intance = JobScheduler::new().await?;
    
    match scheduler_intance.start().await {
        Err(e) => {
            tracing::error!("scheduler start error: {}", e);
            return Ok(());
        },
        _ => (),
    };

    let mut job = Job::new("1/5 * * * * *", move |uuid, _l| {
            info!("{} {}", uuid.to_string(), "I run every 5 seconds");
        }).unwrap();
    
    let remove_uid = job.on_removed_notification_add(&scheduler_intance, Box::new(|job_id, notification_id, type_of_notification| {
        Box::pin(async move {
            println!("Job {:?} was removed, notification {:?} ran ({:?})", job_id, notification_id, type_of_notification);
        })
    })).await?;

    let job_uuid = job.guid();
    let job_uid = scheduler_intance
        .add(job)
        .await.unwrap();
    info!("intervel job: {job_uid:?}, {job_uuid:?}");

    tokio::time::sleep(tokio::time::Duration::from_secs(15)).await;
    match scheduler_intance.remove(&job_uid).await {
        Err(e) => {
            tracing::error!("scheduler remove error: {}", e);
            return Ok(());
        },
        _ => (),
    }

    tokio::time::sleep(tokio::time::Duration::from_secs(120)).await;
    
    Ok(())
}
```

```toml
[package]
name = "aky_vlm_lab"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio = { version = "1.44.0", features = ["full"] }
# schedule
anyhow.workspace = true
tokio-cron-scheduler = {version = "0.13.0", features = ["log", "signal", "postgres_storage"] }

[build-dependencies]
dotenv.workspace = true
# cpp
cmake = "0.1.54"

[[bin]]
name = "schedule"
path = "src/schedule/schedule.rs"


[[bin]]
name = "selfschedule"
path = "src/self_schedule/test.rs"

```
